### ISSUE TITLE
icon not rendered correctly

### ISSUE THREAD

**Issue by newton108** [ashthespy/Atom-LaTeX#221]
<img width="836" alt="Screenshot 2019-09-20 at 13 48 59" src="https://user-images.githubusercontent.com/3450659/65324860-b2606e00-dbad-11e9-85aa-fd7fd3a2090c.png">

Happens every time I run the application. Back to normal, occasionally, after the theme is changed to a different one and changed back.  Any idea how this happened?

**Comment by ashthespy** [comment]
@newton108 More info about version of Atom/OS etc?

**Comment by newton108** [comment]
> @newton108 More info about version of Atom/OS etc?

Thank you for the reply. Atom version 1.40.1, macOS 10.14.6. It occurred in two separate machine, however I do use iCloud to sync the folder .atom. But I'm quite reluctant to believe that's the problem since anything else works quite well.

**Comment by ashthespy** [comment]
The fonts being uses should be available in `.atom/packages/atom-latex/fonts/`
and area loaded simply as:
```less
@font-face {
  font-family: 'FontAwesome';
  font-weight: normal;
  font-style: normal;
  src: url(atom://atom-latex/fonts/fontawesome-webfont.woff2);
}
```
I am unsure why some fonts seems to be rendering for you, and some don't. Honestly, I wouldn't really know how to debug this..
